kind: pipeline
type: docker
name: build

steps:
- name: compile
  image: ubuntu:focal
  commands:
  - bash build.sh

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: token
    files: amlogic-s9xxx-openwrt/out/*
  when:
    event: tag
